src/apps/transferencias/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy


app_name ="transferencias"
urlpatterns = [
    path("comprobante/<int:pk>", views.Comprobante.as_view(), name="comprobante"),
    path("listado/", views.TransferenciaListView.as_view(), name="listado"),
    path("crear/", views.TransferenciaCreateView.as_view(), name="crear"),
    # MOTIVOS
    path('motivos/', views.Motivos.as_view(), name='motivos'),
    path('motivos/eliminar/<int:pk>', views.MotivoDeleteView.as_view(), name='motivos_eliminar'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.urls import reverse_lazy


app_name ="usuarios"
urlpatterns = [
    # vistas USUARIO REGISTRADO
    path("registrados/inicio/", views.UsuarioRegistradoInicio.as_view(), name="registrados_inicio"),
    path("registrados/transferir/", views.TransferirUsuarioRegistrado.as_view(), name="registrados_transferir"),
    path("registrados/movimientos/", views.MovimientosUsuarioRegistrado.as_view(), name="registrados_movimientos"),
    path("registrados/perfil/", views.UsuarioRegistradoPerfil.as_view(), name="registrados_perfil"),
    path("editar/<int:pk>", views.EditarUsuarioRegistrado.as_view(), name="editar"),
    path('registrados/editar_foto/', views.EditarFotoPerfilView.as_view(), name='editar_foto'),
    path('registrados/ingresar/', views.UsuarioRegistradoIngresar.as_view(), name='registrados_ingresar'),
    path('registrados/retirar/', views.UsuarioRegistradoRetirar.as_view(), name='registrados_retirar'),

    # vistas ADMIN
    path("listado/", views.UsuarioListView.as_view(), name="listado"),
    path("perfil/<int:pk>", views.UsuarioDetailView.as_view(), name="perfil"),
    path("cambiar_estado/<int:pk>", views.CambiarEstadoUsuarioView.as_view(), name="cambiar_estado"),
    path("ingresar_dinero/<int:pk>", views.IngresarDinero.as_view(), name="ingresar_dinero"),
    path("retirar_dinero/<int:pk>", views.RetirarDinero.as_view(), name="retirar_dinero"),
    path("actividad/", views.Actividad.as_view(), name="actividad"),

    # vistas USUARIO NO REGISTRADO
    path("crear/", views.UsuarioCreateView.as_view(), name="crear"),


]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from apps.usuarios import views as views_usuarios
from django.contrib.auth import views as views_django
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # prueba /generales
    path('admin/', admin.site.urls),
    path("base/", views.prueba, name="base"),
    # apps
    path("usuarios/", include("apps.usuarios.urls")),
    path("transferencias/", include("apps.transferencias.urls")),
    # login y logout
    path('accounts/login/', views_usuarios.CustomLoginView.as_view(), name='login'),
    path("logout/", views_django.logout_then_login, name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ECOM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>

        {% if user.is_admin %}
            {% block content_gral_admin %}{% endblock content_gral_admin %}
        {% else %}
            <div class="position-relative container">
              <div class="position-absolute top-0 start-50 translate-middle-x p-2" >
                  {% block content_gral %}{% endblock content_gral %}
              </div>
            </div>
        {% endif %}

        <div class="position-relative container">
          <div class="position-absolute top-0 start-50 translate-middle-x p-2" >
              {% block COMPROBANTE %}{% endblock COMPROBANTE %}
          </div>
        </div>
        
              {% comment %} 
              clores base de ECOM (de claro a oscuro)
                #F2F2F2 
                #592045
                #A66388
                #8C4265
                #A62D59

              {% endcomment %}
        
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/menu.html
{% extends 'base.html' %} {% block content_gral_admin %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background: #F2F2F2;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#"><img src="https://ecom.com.ar/img/Logo-Ecom.svg" alt="Logo" width="80" height="20"></a>
        <a class="nav-link" href="#">EcomCash > admin > {{user.first_name}} {{user.last_name}} </b></a>

        <a class="nav-link" href="{% url 'usuarios:listado' %}">Usuarios</a>

        <a class="nav-link"href="{% url 'transferencias:motivos' %}">Motivos</a>
        
        <a class="nav-link"href="{% url 'usuarios:actividad' %}">Actividad</a>

        <form action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <button class="nav-link" type="submit">Cerrar sesion</button>
        </form>       
      </div>
    </div>
  </div>
</nav>

<div class="container">
{% block contenido %} {% endblock contenido %}  
</div>    
{% endblock %}