src/apps/transferencias/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy


app_name ="transferencias"
urlpatterns = [
    path("comprobante/<int:pk>", views.Comprobante.as_view(), name="comprobante"),
    path("listado/", views.TransferenciaListView.as_view(), name="listado"),
    path("crear/", views.TransferenciaCreateView.as_view(), name="crear"),
    # MOTIVOS
    path('motivos/', views.Motivos.as_view(), name='motivos'),
    path('motivos/eliminar/<int:pk>', views.MotivoDeleteView.as_view(), name='motivos_eliminar'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.urls import reverse_lazy


app_name ="usuarios"
urlpatterns = [
    # vistas USUARIO REGISTRADO
    path("registrados/inicio/", views.UsuarioRegistradoInicio.as_view(), name="registrados_inicio"),
    path("registrados/transferir/", views.TransferirUsuarioRegistrado.as_view(), name="registrados_transferir"),
    path("registrados/movimientos/", views.MovimientosUsuarioRegistrado.as_view(), name="registrados_movimientos"),
    path("registrados/perfil/", views.UsuarioRegistradoPerfil.as_view(), name="registrados_perfil"),
    path("editar/<int:pk>", views.EditarUsuarioRegistrado.as_view(), name="editar"),
    path('registrados/editar_foto/', views.EditarFotoPerfilView.as_view(), name='editar_foto'),
    path('registrados/ingresar/', views.UsuarioRegistradoIngresar.as_view(), name='registrados_ingresar'),
    path('registrados/retirar/', views.UsuarioRegistradoRetirar.as_view(), name='registrados_retirar'),

    # vistas ADMIN
    path("listado/", views.UsuarioListView.as_view(), name="listado"),
    path("perfil/<int:pk>", views.UsuarioDetailView.as_view(), name="perfil"),
    path("cambiar_estado/<int:pk>", views.CambiarEstadoUsuarioView.as_view(), name="cambiar_estado"),
    path("ingresar_dinero/<int:pk>", views.IngresarDinero.as_view(), name="ingresar_dinero"),
    path("retirar_dinero/<int:pk>", views.RetirarDinero.as_view(), name="retirar_dinero"),
    path("actividad/", views.Actividad.as_view(), name="actividad"),

    # vistas USUARIO NO REGISTRADO
    path("crear/", views.UsuarioCreateView.as_view(), name="crear"),


]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from apps.usuarios import views as views_usuarios
from django.contrib.auth import views as views_django
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # prueba /generales
    path('admin/', admin.site.urls),
    path("base/", views.prueba, name="base"),
    # apps
    path("usuarios/", include("apps.usuarios.urls")),
    path("transferencias/", include("apps.transferencias.urls")),
    # login y logout
    path('accounts/login/', views_usuarios.CustomLoginView.as_view(), name='login'),
    path("logout/", views_django.logout_then_login, name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    cvu = models.AutoField(primary_key=True, unique=True)
    dni = models.IntegerField(default=0)
    cuil = models.IntegerField(default=0)
    saldo = models.FloatField(default=0, blank=True)
      # Asegurar unicidad en la base de datos
    # campo para saber si es administrador, por defecto no lo es
    is_admin = models.BooleanField(default=False)
    foto_perfil = models.ImageField(default="default.png",upload_to='fotos_perfil/', null=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

src/apps/usuarios/forms.py
from django import forms
from .models import Usuario
from apps.transferencias.models import Transferencia
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm


# personalizacion del login
class LoginFormUsuario(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"id": "usuario",'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
        label="Usuario"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "password",'class': 'form-control', 'placeholder': 'Contraseña'}),
        label="Contraseña"
    )

class CrearFormUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = "__all__"
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()


class FormTransferencia(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "cvu_destino", "motivo"]


class FormRetiro(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto",  "motivo"]


class FormIngreso(forms.ModelForm):
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "motivo"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()



class FormUsuarioRegistradoEditar(forms.ModelForm):
    class Meta:
        model = Usuario
        # solo muestra estos dos campos
        fields = ["dni", "cuil","first_name", "last_name", "email", "password"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()




# usuario registrado > EDITAR foto perfil
class FotoPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['foto_perfil']
        widgets = {
            'foto_perfil': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

src/apps/usuarios/views.py
from django.shortcuts import render
# importacion del modelo
from .models import Usuario
# importacion generic views de django
from django.views.generic.list import ListView
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import DeleteView, CreateView
from django.contrib.auth.views import LoginView, LogoutView

####
from django.urls import reverse_lazy
from django.contrib import messages
from django import forms

###
from .forms import CrearFormUsuario, FormTransferencia, LoginFormUsuario, FormIngreso, FormUsuarioRegistradoEditar, FormRetiro

from apps.transferencias.models import Transferencia, Motivo
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


                # VISTAS USUARIO REGISTRADO
from django.db.models import Q

# usuario registrado > PERFIL
class UsuarioRegistradoPerfil(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/perfil.html'

# usuario registrado > INICIO
class UsuarioRegistradoInicio(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user  # Usuario autenticado
        context['user_info'] = {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'saldo': user.saldo,
            # Agrega más información si es necesario
        }
        return context
    
# usuario registrado > MOVIMIENTOS
class MovimientosUsuarioRegistrado(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/registrados/movimientos.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context

# usuario registrado > TRANSFERIR
class TransferirUsuarioRegistrado(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = "usuarios/registrados/transferir.html"
    context_object_name = "transferencia"
    form_class = FormTransferencia
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')
        cvu_usuario_destino = form.cleaned_data.get('cvu_destino')
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context

# usuario registrado > EDITAR
class EditarUsuarioRegistrado(LoginRequiredMixin, UpdateView):
    model = Usuario
    template_name = "usuarios/registrados/editar.html"
    # atributos que quiero modificar
    form_class = FormUsuarioRegistradoEditar
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_perfil')

from .forms import FotoPerfilForm

class EditarFotoPerfilView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = FotoPerfilForm
    template_name = 'usuarios/registrados/editar_foto_perfil.html'

    def get_object(self):
        # Retorna el usuario actualmente autenticado
        return self.request.user

    def get_success_url(self):
        # Redirige al perfil del usuario o donde desees
        return reverse_lazy('usuarios:registrados_perfil')


class UsuarioRegistradoIngresar(TemplateView):
    template_name = 'usuarios/registrados/registrados_ingresar.html'

#  de retiro
class UsuarioRegistradoRetirar(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = 'usuarios/registrados/retiro.html'
    context_object_name = "transferencia"
    form_class = FormRetiro
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')

        cvu_usuario_destino = 0
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context



                # VISTAS ADMIN
# admin > ACTIVIDAD

class Actividad(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/admin/actividad.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context


# admin > LISTADO USUARIOS
class UsuarioListView(ListView):
    model = Usuario
    template_name = "usuarios/admin/listado.html"
    context_object_name = "usuarios"
    paginate_by = 20  # Opcional: Para paginación

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q') # aplicar filtros a la busqueda
        
        try:
            if query:
                queryset = queryset.filter(cvu=query)  # Filtra según el término
            return queryset
        except:
            return queryset # error Z>>>>>


# admin > PERFIL USUARIO REGISTRADO
class UsuarioDetailView(DetailView):
    model = Usuario
    template_name = "usuarios/perfil.html"
    context_object_name = "usuario"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.object

src/templates/usuarios/admin/actividad.html
{% extends 'menu.html' %} {% block contenido %}



<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nro. transferencia</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Usuario afectado</th>
        <th scope="col">CVU</th>
        <th scope="col">Apellido</th>
        <th scope="col">Nombre</th>        
        <th scope="col">Monto</th>
        <th scope="col">Motivo</th>
      </tr>
    </thead>
    <tbody>
        {% for transferencia in transferencias %}
            
              <tr>
                    <td>{{transferencia.id}}</td>
                    {% if transferencia.destino == user %}
                        <td>EXTRACCION</td>
                        <td>{{transferencia.origen}}</td>
                        <td>{{transferencia.origen.cvu}}</td>
                        <td>{{transferencia.origen.last_name}}</td>
                        <td>{{transferencia.origen.first_name}}</td>
                    {% else %}
                        <td>INGRESO</td>
                        <td>{{transferencia.destino}}</td>
                        <td>{{transferencia.destino.cvu}}</td>
                        <td>{{transferencia.destino.last_name}}</td>
                        <td>{{transferencia.destino.first_name}}</td>
                    {% endif %}
                    <td>{{transferencia.monto}}</td>
                    <td>{{transferencia.motivo}}</td>
                  <td><a class="nav-link" href="{% url 'transferencias:comprobante' transferencia.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                      <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                      <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                    </svg>
                  </a></td>
              </tr>
        {% endfor %}
    </tbody>
        
  </table>

{% endblock %}

src/templates/usuarios/admin/cambiar_estado.html
{% extends 'menu.html' %} {% block contenido %}

{% comment %} 
<div class="container mt-4">
    <h2>Cambiar Estado de Usuario</h2>
    
    
    <p>El usuario está actualmente: <strong>{{ usuario.is_active|yesno:"Activo,Inactivo" }}</strong></p> 
    <form method="post" novalidate>
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">
            Cambiar Estado
        </button>
        <a class="btn btn-secondary" href="{% url 'usuarios:perfil' usuario.cvu %}">Cancelar</a>
    </form>
</div>





# admin > CAMBIAR ESTADO
class CambiarEstado(UpdateView):
    model = Usuario
    template_name = "usuarios/admin/cambiar_estado.html"
    # atributos que quiero modificar
    fields = ["is_active"]
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:listado')
{% endcomment %}






<form method="post" class="container" novalidate>{% csrf_token %}
    

    el usuario {{usuario}}
    esta actualmente
    {{form.is_active}}
    {% if usuario.is_active %}
        ACTIVO
    {% else %}
        INACTIVO
    {% endif %}


    <button class="btn btn-outline-secondary" type="submit">Cambiar</button>
    <a class="btn btn-outline-secondary" href="{% url 'usuarios:perfil' usuario.cvu %}">Cancelar</a>
</form> 

{% endblock %}

src/templates/usuarios/admin/ingresar_dinero.html
{% extends 'menu.html' %} {% block contenido %}
<div class="row">
    <div class="col-4">
        <form method="post" class="">
            {% csrf_token %}

                {% for elemento in form %}
                    <div class="input-group mb-3">
                        <span class="input-group-text">{{ elemento.label }}</span>
                        {{elemento}}
                        <div class="form-text">{{elemento.errors}}</div>
                    </div>
                    
                {% endfor %}
            <button type="submit" class="btn btn-outline-secondary">Ingresar</button>
        </form>
</div>
</div>
{% endblock %}

src/templates/usuarios/admin/listado.html
{% extends 'menu.html' %} {% block contenido %}

<div class="row">
  <!-- Formulario de búsqueda -->
  <form method="get" action="{% url 'usuarios:listado' %}" class="col-4">
        
      <div class="input-group mb-3 col-6">
        <span class="input-group-text">Buscar por cvu</span>  
        <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}" class="form-control">
        <button type="submit" class="btn btn-outline-secondary input-group-text">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
          </svg>
        </button>
      </div>
  </form>
</div>
  <!-- Tabla resultados -->
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">CVU</th>
        <th scope="col">usuario</th>
        <th scope="col">DNI</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Saldo</th>
        <th scope="col">Estado</th>

      </tr>
    </thead>
    <tbody>
        {% for us in usuarios%}
            {% if not us.is_admin %}
              <tr>
                  <td>{{us.cvu}}</td>
                  <td>{{us.username}}</td>
                  <td>{{us.dni}}</td>
                  <td>{{us.first_name}}</td>
                  <td>{{us.last_name}}</td>
                  <td>{{us.saldo}}</td>
                  {% if us.is_active %}
                  <td>activo</td>
                  {% else %}
                  <td>inactivo</td>
                  {% endif %}
                  <td><a class="nav-link" href="{% url 'usuarios:perfil' us.cvu %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                      <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                      <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                    </svg>
                  </a></td>
              </tr>
              {% endif %}
        {% endfor %}
    </tbody>
        
  </table>

      


  {% endblock %}

src/templates/usuarios/admin/retirar_dinero.html
{% extends 'menu.html' %} {% block contenido %}
<div class="row">
    <div class="col-4">
        <form method="post" class="">
            {% csrf_token %}

                {% for elemento in form %}
                    <div class="input-group mb-3">
                        <span class="input-group-text">{{ elemento.label }}</span>
                        {{elemento}}
                        <div class="form-text">{{elemento.errors}}</div>
                    </div>
                    
                {% endfor %}
            <button type="submit" class="btn btn-outline-secondary">Retirar</button>
        </form>
</div>
</div>
{% endblock %}