src/apps/transferencias/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy


app_name ="transferencias"
urlpatterns = [
    path("comprobante/<int:pk>", views.Comprobante.as_view(), name="comprobante"),
    path("listado/", views.TransferenciaListView.as_view(), name="listado"),
    path("crear/", views.TransferenciaCreateView.as_view(), name="crear"),
    # MOTIVOS
    path('motivos/', views.Motivos.as_view(), name='motivos'),
    path('motivos/eliminar/<int:pk>', views.MotivoDeleteView.as_view(), name='motivos_eliminar'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.urls import reverse_lazy


app_name ="usuarios"
urlpatterns = [
    # vistas USUARIO REGISTRADO
    path("registrados/inicio/", views.UsuarioRegistradoInicio.as_view(), name="registrados_inicio"),
    path("registrados/transferir/", views.TransferirUsuarioRegistrado.as_view(), name="registrados_transferir"),
    path("registrados/movimientos/", views.MovimientosUsuarioRegistrado.as_view(), name="registrados_movimientos"),
    path("registrados/perfil/", views.UsuarioRegistradoPerfil.as_view(), name="registrados_perfil"),
    path("editar/<int:pk>", views.EditarUsuarioRegistrado.as_view(), name="editar"),
    path('registrados/editar_foto/', views.EditarFotoPerfilView.as_view(), name='editar_foto'),
    path('registrados/ingresar/', views.UsuarioRegistradoIngresar.as_view(), name='registrados_ingresar'),
    path('registrados/retirar/', views.UsuarioRegistradoRetirar.as_view(), name='registrados_retirar'),

    # vistas ADMIN
    path("listado/", views.UsuarioListView.as_view(), name="listado"),
    path("perfil/<int:pk>", views.UsuarioDetailView.as_view(), name="perfil"),
    path("cambiar_estado/<int:pk>", views.CambiarEstadoUsuarioView.as_view(), name="cambiar_estado"),
    path("ingresar_dinero/<int:pk>", views.IngresarDinero.as_view(), name="ingresar_dinero"),
    path("retirar_dinero/<int:pk>", views.RetirarDinero.as_view(), name="retirar_dinero"),
    path("actividad/", views.Actividad.as_view(), name="actividad"),

    # vistas USUARIO NO REGISTRADO
    path("crear/", views.UsuarioCreateView.as_view(), name="crear"),


]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from apps.usuarios import views as views_usuarios
from django.contrib.auth import views as views_django
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # prueba /generales
    path('admin/', admin.site.urls),
    path("base/", views.prueba, name="base"),
    # apps
    path("usuarios/", include("apps.usuarios.urls")),
    path("transferencias/", include("apps.transferencias.urls")),
    # login y logout
    path('accounts/login/', views_usuarios.CustomLoginView.as_view(), name='login'),
    path("logout/", views_django.logout_then_login, name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    cvu = models.AutoField(primary_key=True, unique=True)
    dni = models.IntegerField(default=0)
    cuil = models.IntegerField(default=0)
    saldo = models.FloatField(default=0, blank=True)
      # Asegurar unicidad en la base de datos
    # campo para saber si es administrador, por defecto no lo es
    is_admin = models.BooleanField(default=False)
    foto_perfil = models.ImageField(default="default.png",upload_to='fotos_perfil/', null=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

src/apps/usuarios/forms.py
from django import forms
from .models import Usuario
from apps.transferencias.models import Transferencia
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm


# personalizacion del login
class LoginFormUsuario(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"id": "usuario",'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
        label="Usuario"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "password",'class': 'form-control', 'placeholder': 'Contraseña'}),
        label="Contraseña"
    )

class CrearFormUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = "__all__"
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()


class FormTransferencia(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "cvu_destino", "motivo"]


class FormRetiro(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto",  "motivo"]


class FormIngreso(forms.ModelForm):
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "motivo"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()



class FormUsuarioRegistradoEditar(forms.ModelForm):
    class Meta:
        model = Usuario
        # solo muestra estos dos campos
        fields = ["dni", "cuil","first_name", "last_name", "email", "password"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()




# usuario registrado > EDITAR foto perfil
class FotoPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['foto_perfil']
        widgets = {
            'foto_perfil': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

src/apps/usuarios/views.py
from django.shortcuts import render
# importacion del modelo
from .models import Usuario
# importacion generic views de django
from django.views.generic.list import ListView
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import DeleteView, CreateView
from django.contrib.auth.views import LoginView, LogoutView

####
from django.urls import reverse_lazy
from django.contrib import messages
from django import forms

###
from .forms import CrearFormUsuario, FormTransferencia, LoginFormUsuario, FormIngreso, FormUsuarioRegistradoEditar, FormRetiro

from apps.transferencias.models import Transferencia, Motivo
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


                # VISTAS USUARIO REGISTRADO
from django.db.models import Q

# usuario registrado > PERFIL
class UsuarioRegistradoPerfil(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/perfil.html'

# usuario registrado > INICIO
class UsuarioRegistradoInicio(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user  # Usuario autenticado
        context['user_info'] = {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'saldo': user.saldo,
            # Agrega más información si es necesario
        }
        return context
    
# usuario registrado > MOVIMIENTOS
class MovimientosUsuarioRegistrado(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/registrados/movimientos.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context

# usuario registrado > TRANSFERIR
class TransferirUsuarioRegistrado(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = "usuarios/registrados/transferir.html"
    context_object_name = "transferencia"
    form_class = FormTransferencia
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')
        cvu_usuario_destino = form.cleaned_data.get('cvu_destino')
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context

# usuario registrado > EDITAR
class EditarUsuarioRegistrado(LoginRequiredMixin, UpdateView):
    model = Usuario
    template_name = "usuarios/registrados/editar.html"
    # atributos que quiero modificar
    form_class = FormUsuarioRegistradoEditar
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_perfil')

from .forms import FotoPerfilForm

class EditarFotoPerfilView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = FotoPerfilForm
    template_name = 'usuarios/registrados/editar_foto_perfil.html'

    def get_object(self):
        # Retorna el usuario actualmente autenticado
        return self.request.user

    def get_success_url(self):
        # Redirige al perfil del usuario o donde desees
        return reverse_lazy('usuarios:registrados_perfil')


class UsuarioRegistradoIngresar(TemplateView):
    template_name = 'usuarios/registrados/registrados_ingresar.html'

#  de retiro
class UsuarioRegistradoRetirar(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = 'usuarios/registrados/retiro.html'
    context_object_name = "transferencia"
    form_class = FormRetiro
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')

        cvu_usuario_destino = 0
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context



                # VISTAS ADMIN
# admin > ACTIVIDAD

class Actividad(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/admin/actividad.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context


# admin > LISTADO USUARIOS
class UsuarioListView(ListView):
    model = Usuario
    template_name = "usuarios/admin/listado.html"
    context_object_name = "usuarios"
    paginate_by = 20  # Opcional: Para paginación

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q') # aplicar filtros a la busqueda
        
        try:
            if query:
                queryset = queryset.filter(cvu=query)  # Filtra según el término
            return queryset
        except:
            return queryset # error Z>>>>>


# admin > PERFIL USUARIO REGISTRADO
class UsuarioDetailView(DetailView):
    model = Usuario
    template_name = "usuarios/perfil.html"
    context_object_name = "usuario"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.object

src/templates/usuarios/eliminar.html
<h1>ELIMINAR USUARIO</h1>

src/templates/usuarios/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ECOM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background: #fff;">
        <div class="position-relative container">
            <div class="position-absolute top-0 start-50 translate-middle-x p-3" >

                
                <div class="card text-center" style="width: 30rem;background: #fff;">
                    <div class="card-header" style="background: #F2F2F2;">
                            {% comment %} LOGO ECOM {% endcomment %}
                            <img src="https://ecom.com.ar/img/Logo-Ecom.svg" alt="Logo" width="300" height="165">

                            <h1 class="h3 fw-normal card-title">EcomCash</h1>
                    </div>
                    <div class="card-body">
                        <form method="post">{% csrf_token %}
                                

                                <div class="mb-3">
                                    {{form.username}}
                                    <div id="usuario" class="form-text">{{form.username.errors}}</div>
                                </div>
                                <div class="mb-3">
                                    {{form.password}}
                                    <div id="password" class="form-text">{{form.password.errors}}</div>
                                </div>
                                <div id="password" class="form-text">{{form.errors}}</div>
                                <button type="submit" class="btn btn-primary rounded-pill" style="background: #A62D59;">Iniciar sesion</button>
                            
                        </form>

                    </div>
                    <div class="card-footer text-body-secondary" style="background: #F2F2F2;">
                        <a class="nav-link mt-2"href="{% url 'usuarios:crear' %}">Crear nuevo usuario</a>
                    </div>
                </div>  
            </div>
        </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/usuarios/perfil.html
{% extends 'menu.html' %} {% block contenido %}


<div class="row">
    <div class="col-2">
        {% if usuario.foto_perfil %}
            <img src="{{ usuario.foto_perfil.url }}" alt="Foto de perfil" class="" style="width: 200px; height: 200px; object-fit: cover;">

        {% else %}
            <img src="{{ "/media/default.png" }}" alt="Foto de perfil" class="" style="width: 200px; height: 200px; object-fit: cover;">

        {% endif %}
    </div>
    <div class="col-3">
        <h5> Usuario: {{usuario.username}} </h5>
        <h5> CVU: {{usuario.cvu}} </h5>
        <h5> Nombre: {{usuario.first_name}} </h5>
        <h5> Apellido: {{usuario.last_name}} </h5>
        <h5> DNI: {{usuario.dni}} </h5>
        <h5> CUIL: {{usuario.cuil}} </h5>
    </div>
    <div class="col-3 text-center">
        <div class="m-3">
            <h5> SALDO </h5>
            <h5> {{usuario.saldo}} </h5>
        </div>
        <div class="m-3">

            {% if usuario.is_active %}
                <h5> USUARIO ACTIVO </h5>
            {% else %}
                <h5>  USUARIO INACTIVO </h5>
            {% endif %}
            <a class="nav-link"href="{% url 'usuarios:cambiar_estado' usuario.cvu %}">Cambiar estado</a>
        </div>
    </div>
    <div class="col-3 text-center mx-auto p-2">
        <div class="m-3">
            <a href="{% url 'usuarios:ingresar_dinero' usuario.cvu %}" type="button" class="btn btn-outline-success"><h5> INGRESAR DINERO </h5></a>
        </div>
        <div class="m-3">
            <a href="{% url 'usuarios:retirar_dinero' usuario.cvu %}" type="button" class="btn btn-outline-success"><h5> RETIRAR DINERO </h5></a>

            
        </div>
    </div>
</div>
{% comment %} LISTADOOO {% endcomment %}
{% if transferencias %}
<table class="table table-striped">
    <thead>
            <tr>
                <th scope="col">Descripcion</th>
                <th scope="col">Origen</th>
                <th scope="col">Destino</th>
                <th scope="col">Fecha</th>
                <th scope="col">Monto</th>
            </tr>
    </thead>
    <tbody>
        {% for transferencia in transferencias %}
            <tr>
                {% if transferencia.destino.is_admin %}
                        <td>
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-up m-1" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1z"/>
                                <path fill-rule="evenodd" d="M7.646.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 1.707V10.5a.5.5 0 0 1-1 0V1.707L5.354 3.854a.5.5 0 1 1-.708-.708z"/>
                            </svg>
                            Retiro dinero
                        </td>
                {% else %}
                        {% if transferencia.origen.is_admin %}
                                <td>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-in-down m-1" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1z"/>
                                        <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                                    </svg> 
                                    Ingreso dinero
                                </td>
                        {% else %}
                                    {% if transferencia.destino == usuario %}
                                                    <td>
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-in-left m-1" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
                                                            <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                                                        </svg> 
                                                        Recibio dinero
                                                    </td>
                                    {% else %}
                                                    <td> 
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right m-1" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                                        </svg>
                                                        Envio dinero
                                                    </td>
                                    {% endif %}
                        {% endif %}
                {% endif %}
                
                <td>  {{transferencia.origen}} </td>
                <td>  {{transferencia.destino}} </td>
                <td>  {{transferencia.fecha}} </td>
                <td>  {{transferencia.monto}} </td>
                <td><a class="nav-link" href="{% url 'transferencias:comprobante' transferencia.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                      <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                      <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                    </svg>
                  </a></td>
            </tr>
        {% endfor %}
    </tbody>
          
    </table>
{% else %}
No tiene movimientos...
{% endif %}









<ul>
    
</ul>

       
{% endblock %}