src/apps/transferencias/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy


app_name ="transferencias"
urlpatterns = [
    path("comprobante/<int:pk>", views.Comprobante.as_view(), name="comprobante"),
    path("listado/", views.TransferenciaListView.as_view(), name="listado"),
    path("crear/", views.TransferenciaCreateView.as_view(), name="crear"),
    # MOTIVOS
    path('motivos/', views.Motivos.as_view(), name='motivos'),
    path('motivos/eliminar/<int:pk>', views.MotivoDeleteView.as_view(), name='motivos_eliminar'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views
# importacion para el logout
from django.urls import reverse_lazy


app_name ="usuarios"
urlpatterns = [
    # vistas USUARIO REGISTRADO
    path("registrados/inicio/", views.UsuarioRegistradoInicio.as_view(), name="registrados_inicio"),
    path("registrados/transferir/", views.TransferirUsuarioRegistrado.as_view(), name="registrados_transferir"),
    path("registrados/movimientos/", views.MovimientosUsuarioRegistrado.as_view(), name="registrados_movimientos"),
    path("registrados/perfil/", views.UsuarioRegistradoPerfil.as_view(), name="registrados_perfil"),
    path("editar/<int:pk>", views.EditarUsuarioRegistrado.as_view(), name="editar"),
    path('registrados/editar_foto/', views.EditarFotoPerfilView.as_view(), name='editar_foto'),
    path('registrados/ingresar/', views.UsuarioRegistradoIngresar.as_view(), name='registrados_ingresar'),
    path('registrados/retirar/', views.UsuarioRegistradoRetirar.as_view(), name='registrados_retirar'),

    # vistas ADMIN
    path("listado/", views.UsuarioListView.as_view(), name="listado"),
    path("perfil/<int:pk>", views.UsuarioDetailView.as_view(), name="perfil"),
    path("cambiar_estado/<int:pk>", views.CambiarEstadoUsuarioView.as_view(), name="cambiar_estado"),
    path("ingresar_dinero/<int:pk>", views.IngresarDinero.as_view(), name="ingresar_dinero"),
    path("retirar_dinero/<int:pk>", views.RetirarDinero.as_view(), name="retirar_dinero"),
    path("actividad/", views.Actividad.as_view(), name="actividad"),

    # vistas USUARIO NO REGISTRADO
    path("crear/", views.UsuarioCreateView.as_view(), name="crear"),


]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from apps.usuarios import views as views_usuarios
from django.contrib.auth import views as views_django
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # prueba /generales
    path('admin/', admin.site.urls),
    path("base/", views.prueba, name="base"),
    # apps
    path("usuarios/", include("apps.usuarios.urls")),
    path("transferencias/", include("apps.transferencias.urls")),
    # login y logout
    path('accounts/login/', views_usuarios.CustomLoginView.as_view(), name='login'),
    path("logout/", views_django.logout_then_login, name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    cvu = models.AutoField(primary_key=True, unique=True)
    dni = models.IntegerField(default=0)
    cuil = models.IntegerField(default=0)
    saldo = models.FloatField(default=0, blank=True)
      # Asegurar unicidad en la base de datos
    # campo para saber si es administrador, por defecto no lo es
    is_admin = models.BooleanField(default=False)
    foto_perfil = models.ImageField(default="default.png",upload_to='fotos_perfil/', null=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

src/apps/usuarios/forms.py
from django import forms
from .models import Usuario
from apps.transferencias.models import Transferencia
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm


# personalizacion del login
class LoginFormUsuario(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"id": "usuario",'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
        label="Usuario"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "password",'class': 'form-control', 'placeholder': 'Contraseña'}),
        label="Contraseña"
    )

class CrearFormUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = "__all__"
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()


class FormTransferencia(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "cvu_destino", "motivo"]


class FormRetiro(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto",  "motivo"]


class FormIngreso(forms.ModelForm):
    class Meta:
        model = Transferencia
        # solo muestra estos dos campos
        fields = ["monto", "motivo"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()



class FormUsuarioRegistradoEditar(forms.ModelForm):
    class Meta:
        model = Usuario
        # solo muestra estos dos campos
        fields = ["dni", "cuil","first_name", "last_name", "email", "password"]
    # asigna a todos ditectamete la clase >>>>
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields.values():
            clase_existente = campo.widget.attrs.get('class', '')
            campo.widget.attrs['class'] = f'{clase_existente} form-control'.strip()




# usuario registrado > EDITAR foto perfil
class FotoPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['foto_perfil']
        widgets = {
            'foto_perfil': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

src/apps/usuarios/views.py
from django.shortcuts import render
# importacion del modelo
from .models import Usuario
# importacion generic views de django
from django.views.generic.list import ListView
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import DeleteView, CreateView
from django.contrib.auth.views import LoginView, LogoutView

####
from django.urls import reverse_lazy
from django.contrib import messages
from django import forms

###
from .forms import CrearFormUsuario, FormTransferencia, LoginFormUsuario, FormIngreso, FormUsuarioRegistradoEditar, FormRetiro

from apps.transferencias.models import Transferencia, Motivo
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


                # VISTAS USUARIO REGISTRADO
from django.db.models import Q

# usuario registrado > PERFIL
class UsuarioRegistradoPerfil(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/perfil.html'

# usuario registrado > INICIO
class UsuarioRegistradoInicio(LoginRequiredMixin, TemplateView):
    template_name = 'usuarios/registrados/inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user  # Usuario autenticado
        context['user_info'] = {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'saldo': user.saldo,
            # Agrega más información si es necesario
        }
        return context
    
# usuario registrado > MOVIMIENTOS
class MovimientosUsuarioRegistrado(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/registrados/movimientos.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context

# usuario registrado > TRANSFERIR
class TransferirUsuarioRegistrado(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = "usuarios/registrados/transferir.html"
    context_object_name = "transferencia"
    form_class = FormTransferencia
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')
        cvu_usuario_destino = form.cleaned_data.get('cvu_destino')
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context

# usuario registrado > EDITAR
class EditarUsuarioRegistrado(LoginRequiredMixin, UpdateView):
    model = Usuario
    template_name = "usuarios/registrados/editar.html"
    # atributos que quiero modificar
    form_class = FormUsuarioRegistradoEditar
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_perfil')

from .forms import FotoPerfilForm

class EditarFotoPerfilView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = FotoPerfilForm
    template_name = 'usuarios/registrados/editar_foto_perfil.html'

    def get_object(self):
        # Retorna el usuario actualmente autenticado
        return self.request.user

    def get_success_url(self):
        # Redirige al perfil del usuario o donde desees
        return reverse_lazy('usuarios:registrados_perfil')


class UsuarioRegistradoIngresar(TemplateView):
    template_name = 'usuarios/registrados/registrados_ingresar.html'

#  de retiro
class UsuarioRegistradoRetirar(LoginRequiredMixin, CreateView):
    model = Transferencia
    template_name = 'usuarios/registrados/retiro.html'
    context_object_name = "transferencia"
    form_class = FormRetiro
    
    def form_valid(self, form):
        # EXTRACCION DE DATOS DEL FORM
        monto = form.cleaned_data.get('monto')

        cvu_usuario_destino = 0
        seleccion_motivo = form.cleaned_data.get('seleccion_motivo')
        # CONTROL QUE EL MONTO NO SEA MAYOR AL SALIDO
        if monto > self.request.user.saldo:
            form.add_error('monto', f"Solo tienes {self.request.user.saldo} en tu cuenta")
            return self.form_invalid(form)  # Regresa al formulario con errores
        
        # LOGICA DE LA TRANSFERENCIA

        # conslto si existe el cvu ingresado
        if Usuario.objects.filter(cvu=cvu_usuario_destino):
            # asigno al objeto transferencia, el usuario de destino
            form.instance.destino = Usuario.objects.filter(cvu=cvu_usuario_destino)[0]
            # actualizo el saldo de la cuenta de destino
            nuevo_saldo_d = monto + Usuario.objects.filter(cvu=cvu_usuario_destino)[0].saldo
            Usuario.objects.filter(cvu=cvu_usuario_destino).update(saldo = nuevo_saldo_d)
        else:
            form.add_error('cvu_destino', f"No existe usuario registrado con ese CVU")
            return self.form_invalid(form) 
        
        # obtengo cvu del usuario logueado
        cvu_usuario_logueado=(self.request.user.cvu)
        # nuevo saldo = saldo del usuario logueado - monto de transferencia
        nuevo_saldo = self.request.user.saldo - monto
        # guardo los cambios
        Usuario.objects.filter(cvu=cvu_usuario_logueado).update(saldo = nuevo_saldo)


        #form.instance.motivo = Motivo.objects.filter(motivo=seleccion_motivo)
        print(seleccion_motivo)
        # origen = usuario > por defecto
        form.instance.origen = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        # Generar la URL dinámica en tiempo de ejecución
        return reverse_lazy('usuarios:registrados_inicio')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # obtener todas las transferencias de un usuario
        context["motivos"] = Motivo.objects.all()
        return context



                # VISTAS ADMIN
# admin > ACTIVIDAD

class Actividad(LoginRequiredMixin, TemplateView):
    template_name = "usuarios/admin/actividad.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.request.user
        transferencias = Transferencia.objects.filter(
            Q(origen=usuario) | Q(destino=usuario)
        ).order_by('-fecha')  # Ordenar por fecha descendente

        context["transferencias"] = transferencias
        return context


# admin > LISTADO USUARIOS
class UsuarioListView(ListView):
    model = Usuario
    template_name = "usuarios/admin/listado.html"
    context_object_name = "usuarios"
    paginate_by = 20  # Opcional: Para paginación

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q') # aplicar filtros a la busqueda
        
        try:
            if query:
                queryset = queryset.filter(cvu=query)  # Filtra según el término
            return queryset
        except:
            return queryset # error Z>>>>>


# admin > PERFIL USUARIO REGISTRADO
class UsuarioDetailView(DetailView):
    model = Usuario
    template_name = "usuarios/perfil.html"
    context_object_name = "usuario"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta de base de datos > de todas las transferencias filtrar las que corresponden con el usuario
        # Consulta con Q para filtrar por usuario en origen o destino
        usuario = self.object

src/templates/usuarios/registrados/editar.html
{% extends 'base.html' %} {% block content_gral %}

<div class="">
    <div class="card" style="width: 30rem;">
{% comment %} card-HEADER {% endcomment %}
        <div class="card-header" style="background: #F2F2F2;">
            <a class="col nav-link"href="{% url 'usuarios:registrados_perfil' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
                </svg>                
            </a>
            
        </div>
{% comment %} card-BODY {% endcomment %}

        <div class="card-body">
            <h5>Editar perfil</h5>
            
            <form method="post">{% csrf_token %}
                {% for elemento in form %}
                    <div class="input-group mb-3">
                        <span class="input-group-text">{{ elemento.label }}</span>
                        {{elemento}}
                        <div class="form-text">{{elemento.errors}}</div>
                    </div>
                    
                {% endfor %}
                <button type="submit" class="btn btn-primary rounded-pill" style="background: #A62D59;">Guardar cambios</button>

            </form>

        </div>
    </div>
</div>

       
{% endblock %}

src/templates/usuarios/registrados/editar_foto_perfil.html
{% extends 'base.html' %} {% block content_gral %}

<div class="">
    <div class="card" style="width: 30rem;">
{% comment %} card-HEADER {% endcomment %}
        <div class="card-header text-center" style="background: #F2F2F2;">
            <h4>Editar foto de perfil</h4>
            
        </div>
{% comment %} card-BODY {% endcomment %}

        <div class="card-body position-relative">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary rounded-pill" style="background: #A62D59;">Guardar cambios</button>

                
            </form>

        </div>
{% comment %} card-FOOTER {% endcomment %}
        <div class="card-footer text-body-secondary" style="background: #F2F2F2;">
            <a href="{% url 'usuarios:registrados_perfil' %}" class="nav-link">Volver</a>
        </div>
    </div>
</div>

       
{% endblock %}

src/templates/usuarios/registrados/inicio.html
{% extends 'base.html' %} {% block content_gral %}

<div class="">
    <div class="card" style="width: 30rem;">
{% comment %} card-HEADER {% endcomment %}
        <div class="card-header" style="background: #F2F2F2;">
            <a class="nav-link" href="{% url 'usuarios:registrados_perfil' %}">
                <h5>
                    {% if user.foto_perfil %}
                            <img src="{{ user.foto_perfil.url }}" alt="Foto de perfil" class="" style="width: 25px; height: 25px; border-radius: 50%; object-fit: cover;">
                    {% else %}
                            <img src="{{ "/media/default.png" }}" alt="Foto de perfil" class="" style="width: 25px; height: 25px; border-radius: 50%; object-fit: cover;">
                    
                    {% endif %}
                    {{user.first_name}} {{user.last_name}}</h5>
            </a>
            
        </div>
{% comment %} card-BODY {% endcomment %}

        <div class="card-body">
            <div class="card-text">Dinero disponible</p>
            <h2 class="card-title">$ {{user.saldo}}</h2>

        </div>
{% comment %} card-FOOTER {% endcomment %}
        <div class="card-footer text-body-secondary" style="background: #F2F2F2;">
            <div class="text-center m-2">
                <div class="row">
                    <a class="col nav-link" href="{% url 'usuarios:registrados_transferir' %}">
                        {% comment %} se cambio with. height y se dio margen... {% endcomment %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-right m-1" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                        </svg>
                        <div>Transferir</div>                  
                        
                    </a>
                    <a class="col nav-link" href="{% url 'usuarios:registrados_ingresar' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-down m-1" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1z"/>
                            <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                        </svg>
                    <div>Ingresar</div>
                    <div>dinero</div>  
                    </a>
            
                    <a class="col nav-link" href="{% url 'usuarios:registrados_retirar' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-up m-1" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1z"/>
                            <path fill-rule="evenodd" d="M7.646.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 1.707V10.5a.5.5 0 0 1-1 0V1.707L5.354 3.854a.5.5 0 1 1-.708-.708z"/>
                        </svg>
                    <div>Retirar</div>
                    <div>dinero</div>  
                    </a>
            
                    <a class="col nav-link"href="{% url 'usuarios:registrados_movimientos' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left-right m-1" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 11.5a.5.5 0 0 0 .5.5h11.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 11H1.5a.5.5 0 0 0-.5.5m14-7a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H14.5a.5.5 0 0 1 .5.5"/>
                        </svg>
                    <div>Mis</div>
                    <div>movimientos</div>
                    </a>
        
                </div>
            </div>





            
        </div>
    </div>
</div>

       
{% endblock %}

src/templates/usuarios/registrados/perfil.html
{% extends 'base.html' %} {% block content_gral %}

<div class="">
    <div class="card" style="width: 30rem;">
{% comment %} card-HEADER {% endcomment %}
        <div class="card-header" style="background: #F2F2F2;">
            <a class="col nav-link"href="{% url 'usuarios:registrados_inicio' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
                </svg>                
            </a>
            
        </div>
{% comment %} card-BODY {% endcomment %}

        <div class="card-body position-relative">
            {% if user.foto_perfil %}
                <a href="{% url 'usuarios:editar_foto' %}">
                    <img src="{{ user.foto_perfil.url }}" alt="Foto de perfil" class="position-absolute top-0 start-50 translate-middle" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;">
                </a>
            {% else %}
                <a href="{% url 'usuarios:editar_foto' %}">
                    <img src="{{ "/media/default.png" }}" class="position-absolute top-0 start-50 translate-middle" alt="Foto de perfil" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;">
                </a>
            {% endif %}
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p>CVU: {{user.cvu}}</p>
            <p>Usuario: {{user}}</p>
            <p>DNI: {{user.dni}}</p>
            <p>CUIL: {{user.cuil}}</p>
            <p>Email: {{user.email}}</p>
            <p>Nombre: {{user.first_name}}</p>
            <p>Apellido: {{user.last_name}}</p>
            <a class=""href="{% url 'usuarios:editar' user.cvu %}">
                Editar Perfil
            </a>

        </div>
{% comment %} card-FOOTER {% endcomment %}
        <div class="card-footer text-body-secondary" style="background: #F2F2F2;">
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="nav-link" type="submit">Cerrar sesion</button>
            </form>
        </div>
    </div>
</div>

       
{% endblock %}